version: '3.8'
services:
  db:
    image: postgres:15
    container_name: warhammer_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warhammer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: warhammer_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
